name: 'Android Apk 빌드 & 업로드'
on:
  push:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: 버전 추출하기
        run: echo "::set-output name=VERSION_NAME::$(grep -i "versionName " app/build.gradle | awk '{print $3}')"
        id: version

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug
        run: ./gradlew assembleDebug

      - name: Send APK file to Slack
        env:
          SLACK_TOKEN: ${{ secrets.APP_TOKEN }}
        run: curl https://slack.com/api/files.upload -F token=$APP_TOKEN -F channels=apk-tester -F file=@app/build/outputs/apk/debug/app-debug.apk

      - name: action-slack
        uses: 8398a7/action-slack@v3.8.0
        with:
          status: ${{ job.status }}
          mention: "<!channel>"
          text: "APK를 테스트 해보셔용! (version : ${{ steps.version.outputs.VERSION_NAME }})"
          fields: repo, commit, ref, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
